# Generated by Django 4.1.7 on 2023-03-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
